/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthSigninRouteImport } from './routes/auth/signin'
import { Route as AuthNewPasswordRouteImport } from './routes/auth/new-password'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthEmailVerificationRouteImport } from './routes/auth/email-verification'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as PublicLayoutRouteImport } from './routes/_public/_layout'
import { Route as AuthenticatedDashboardRouteRouteImport } from './routes/_authenticated/dashboard/route'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedDashboardSettingsRouteRouteImport } from './routes/_authenticated/dashboard/settings/route'
import { Route as PublicLayoutsiteIndexRouteImport } from './routes/_public/_layout/(site)/index'
import { Route as AuthenticatedDashboardVulnerabilitiesIndexRouteImport } from './routes/_authenticated/dashboard/vulnerabilities/index'
import { Route as AuthenticatedDashboardSettingsIndexRouteImport } from './routes/_authenticated/dashboard/settings/index'
import { Route as AuthenticatedDashboardScanHistoryIndexRouteImport } from './routes/_authenticated/dashboard/scan-history/index'
import { Route as AuthenticatedDashboardReportsIndexRouteImport } from './routes/_authenticated/dashboard/reports/index'
import { Route as AuthenticatedDashboardPluginsThemesIndexRouteImport } from './routes/_authenticated/dashboard/plugins-themes/index'
import { Route as AuthenticatedDashboardIntegrationsIndexRouteImport } from './routes/_authenticated/dashboard/integrations/index'
import { Route as AuthenticatedDashboardCoreConfigIndexRouteImport } from './routes/_authenticated/dashboard/core-config/index'
import { Route as AuthenticatedDashboardAlertsIndexRouteImport } from './routes/_authenticated/dashboard/alerts/index'
import { Route as PublicLayoutsiteTermsRouteImport } from './routes/_public/_layout/(site)/terms'
import { Route as PublicLayoutsitePrivacyRouteImport } from './routes/_public/_layout/(site)/privacy'
import { Route as PublicLayoutsiteContactRouteImport } from './routes/_public/_layout/(site)/contact'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/auth/signin',
  path: '/auth/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthNewPasswordRoute = AuthNewPasswordRouteImport.update({
  id: '/auth/new-password',
  path: '/auth/new-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthEmailVerificationRoute = AuthEmailVerificationRouteImport.update({
  id: '/auth/email-verification',
  path: '/auth/email-verification',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicLayoutRoute = PublicLayoutRouteImport.update({
  id: '/_public/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRouteRoute =
  AuthenticatedDashboardRouteRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardSettingsRouteRoute =
  AuthenticatedDashboardSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const PublicLayoutsiteIndexRoute = PublicLayoutsiteIndexRouteImport.update({
  id: '/(site)/',
  path: '/',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const AuthenticatedDashboardVulnerabilitiesIndexRoute =
  AuthenticatedDashboardVulnerabilitiesIndexRouteImport.update({
    id: '/vulnerabilities/',
    path: '/vulnerabilities/',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardSettingsIndexRoute =
  AuthenticatedDashboardSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardSettingsRouteRoute,
  } as any)
const AuthenticatedDashboardScanHistoryIndexRoute =
  AuthenticatedDashboardScanHistoryIndexRouteImport.update({
    id: '/scan-history/',
    path: '/scan-history/',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardReportsIndexRoute =
  AuthenticatedDashboardReportsIndexRouteImport.update({
    id: '/reports/',
    path: '/reports/',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardPluginsThemesIndexRoute =
  AuthenticatedDashboardPluginsThemesIndexRouteImport.update({
    id: '/plugins-themes/',
    path: '/plugins-themes/',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardIntegrationsIndexRoute =
  AuthenticatedDashboardIntegrationsIndexRouteImport.update({
    id: '/integrations/',
    path: '/integrations/',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardCoreConfigIndexRoute =
  AuthenticatedDashboardCoreConfigIndexRouteImport.update({
    id: '/core-config/',
    path: '/core-config/',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardAlertsIndexRoute =
  AuthenticatedDashboardAlertsIndexRouteImport.update({
    id: '/alerts/',
    path: '/alerts/',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const PublicLayoutsiteTermsRoute = PublicLayoutsiteTermsRouteImport.update({
  id: '/(site)/terms',
  path: '/terms',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const PublicLayoutsitePrivacyRoute = PublicLayoutsitePrivacyRouteImport.update({
  id: '/(site)/privacy',
  path: '/privacy',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const PublicLayoutsiteContactRoute = PublicLayoutsiteContactRouteImport.update({
  id: '/(site)/contact',
  path: '/contact',
  getParentRoute: () => PublicLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicLayoutsiteIndexRoute
  '/dashboard': typeof AuthenticatedDashboardRouteRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/email-verification': typeof AuthEmailVerificationRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/new-password': typeof AuthNewPasswordRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRouteRouteWithChildren
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/contact': typeof PublicLayoutsiteContactRoute
  '/privacy': typeof PublicLayoutsitePrivacyRoute
  '/terms': typeof PublicLayoutsiteTermsRoute
  '/dashboard/alerts/': typeof AuthenticatedDashboardAlertsIndexRoute
  '/dashboard/core-config/': typeof AuthenticatedDashboardCoreConfigIndexRoute
  '/dashboard/integrations/': typeof AuthenticatedDashboardIntegrationsIndexRoute
  '/dashboard/plugins-themes/': typeof AuthenticatedDashboardPluginsThemesIndexRoute
  '/dashboard/reports/': typeof AuthenticatedDashboardReportsIndexRoute
  '/dashboard/scan-history/': typeof AuthenticatedDashboardScanHistoryIndexRoute
  '/dashboard/settings/': typeof AuthenticatedDashboardSettingsIndexRoute
  '/dashboard/vulnerabilities/': typeof AuthenticatedDashboardVulnerabilitiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicLayoutsiteIndexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/email-verification': typeof AuthEmailVerificationRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/new-password': typeof AuthNewPasswordRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/contact': typeof PublicLayoutsiteContactRoute
  '/privacy': typeof PublicLayoutsitePrivacyRoute
  '/terms': typeof PublicLayoutsiteTermsRoute
  '/dashboard/alerts': typeof AuthenticatedDashboardAlertsIndexRoute
  '/dashboard/core-config': typeof AuthenticatedDashboardCoreConfigIndexRoute
  '/dashboard/integrations': typeof AuthenticatedDashboardIntegrationsIndexRoute
  '/dashboard/plugins-themes': typeof AuthenticatedDashboardPluginsThemesIndexRoute
  '/dashboard/reports': typeof AuthenticatedDashboardReportsIndexRoute
  '/dashboard/scan-history': typeof AuthenticatedDashboardScanHistoryIndexRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsIndexRoute
  '/dashboard/vulnerabilities': typeof AuthenticatedDashboardVulnerabilitiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteRouteWithChildren
  '/_public/_layout': typeof PublicLayoutRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/email-verification': typeof AuthEmailVerificationRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/new-password': typeof AuthNewPasswordRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/_authenticated/dashboard/settings': typeof AuthenticatedDashboardSettingsRouteRouteWithChildren
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_public/_layout/(site)/contact': typeof PublicLayoutsiteContactRoute
  '/_public/_layout/(site)/privacy': typeof PublicLayoutsitePrivacyRoute
  '/_public/_layout/(site)/terms': typeof PublicLayoutsiteTermsRoute
  '/_authenticated/dashboard/alerts/': typeof AuthenticatedDashboardAlertsIndexRoute
  '/_authenticated/dashboard/core-config/': typeof AuthenticatedDashboardCoreConfigIndexRoute
  '/_authenticated/dashboard/integrations/': typeof AuthenticatedDashboardIntegrationsIndexRoute
  '/_authenticated/dashboard/plugins-themes/': typeof AuthenticatedDashboardPluginsThemesIndexRoute
  '/_authenticated/dashboard/reports/': typeof AuthenticatedDashboardReportsIndexRoute
  '/_authenticated/dashboard/scan-history/': typeof AuthenticatedDashboardScanHistoryIndexRoute
  '/_authenticated/dashboard/settings/': typeof AuthenticatedDashboardSettingsIndexRoute
  '/_authenticated/dashboard/vulnerabilities/': typeof AuthenticatedDashboardVulnerabilitiesIndexRoute
  '/_public/_layout/(site)/': typeof PublicLayoutsiteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/auth/callback'
    | '/auth/email-verification'
    | '/auth/forgot-password'
    | '/auth/new-password'
    | '/auth/signin'
    | '/auth/signup'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/contact'
    | '/privacy'
    | '/terms'
    | '/dashboard/alerts/'
    | '/dashboard/core-config/'
    | '/dashboard/integrations/'
    | '/dashboard/plugins-themes/'
    | '/dashboard/reports/'
    | '/dashboard/scan-history/'
    | '/dashboard/settings/'
    | '/dashboard/vulnerabilities/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/callback'
    | '/auth/email-verification'
    | '/auth/forgot-password'
    | '/auth/new-password'
    | '/auth/signin'
    | '/auth/signup'
    | '/dashboard'
    | '/contact'
    | '/privacy'
    | '/terms'
    | '/dashboard/alerts'
    | '/dashboard/core-config'
    | '/dashboard/integrations'
    | '/dashboard/plugins-themes'
    | '/dashboard/reports'
    | '/dashboard/scan-history'
    | '/dashboard/settings'
    | '/dashboard/vulnerabilities'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/dashboard'
    | '/_public/_layout'
    | '/auth/callback'
    | '/auth/email-verification'
    | '/auth/forgot-password'
    | '/auth/new-password'
    | '/auth/signin'
    | '/auth/signup'
    | '/_authenticated/dashboard/settings'
    | '/_authenticated/dashboard/'
    | '/_public/_layout/(site)/contact'
    | '/_public/_layout/(site)/privacy'
    | '/_public/_layout/(site)/terms'
    | '/_authenticated/dashboard/alerts/'
    | '/_authenticated/dashboard/core-config/'
    | '/_authenticated/dashboard/integrations/'
    | '/_authenticated/dashboard/plugins-themes/'
    | '/_authenticated/dashboard/reports/'
    | '/_authenticated/dashboard/scan-history/'
    | '/_authenticated/dashboard/settings/'
    | '/_authenticated/dashboard/vulnerabilities/'
    | '/_public/_layout/(site)/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  PublicLayoutRoute: typeof PublicLayoutRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthEmailVerificationRoute: typeof AuthEmailVerificationRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthNewPasswordRoute: typeof AuthNewPasswordRoute
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/auth/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/new-password': {
      id: '/auth/new-password'
      path: '/auth/new-password'
      fullPath: '/auth/new-password'
      preLoaderRoute: typeof AuthNewPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/email-verification': {
      id: '/auth/email-verification'
      path: '/auth/email-verification'
      fullPath: '/auth/email-verification'
      preLoaderRoute: typeof AuthEmailVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/_layout': {
      id: '/_public/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/settings': {
      id: '/_authenticated/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_public/_layout/(site)/': {
      id: '/_public/_layout/(site)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicLayoutsiteIndexRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_authenticated/dashboard/vulnerabilities/': {
      id: '/_authenticated/dashboard/vulnerabilities/'
      path: '/vulnerabilities'
      fullPath: '/dashboard/vulnerabilities/'
      preLoaderRoute: typeof AuthenticatedDashboardVulnerabilitiesIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/settings/': {
      id: '/_authenticated/dashboard/settings/'
      path: '/'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardSettingsRouteRoute
    }
    '/_authenticated/dashboard/scan-history/': {
      id: '/_authenticated/dashboard/scan-history/'
      path: '/scan-history'
      fullPath: '/dashboard/scan-history/'
      preLoaderRoute: typeof AuthenticatedDashboardScanHistoryIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/reports/': {
      id: '/_authenticated/dashboard/reports/'
      path: '/reports'
      fullPath: '/dashboard/reports/'
      preLoaderRoute: typeof AuthenticatedDashboardReportsIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/plugins-themes/': {
      id: '/_authenticated/dashboard/plugins-themes/'
      path: '/plugins-themes'
      fullPath: '/dashboard/plugins-themes/'
      preLoaderRoute: typeof AuthenticatedDashboardPluginsThemesIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/integrations/': {
      id: '/_authenticated/dashboard/integrations/'
      path: '/integrations'
      fullPath: '/dashboard/integrations/'
      preLoaderRoute: typeof AuthenticatedDashboardIntegrationsIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/core-config/': {
      id: '/_authenticated/dashboard/core-config/'
      path: '/core-config'
      fullPath: '/dashboard/core-config/'
      preLoaderRoute: typeof AuthenticatedDashboardCoreConfigIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/alerts/': {
      id: '/_authenticated/dashboard/alerts/'
      path: '/alerts'
      fullPath: '/dashboard/alerts/'
      preLoaderRoute: typeof AuthenticatedDashboardAlertsIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_public/_layout/(site)/terms': {
      id: '/_public/_layout/(site)/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof PublicLayoutsiteTermsRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_public/_layout/(site)/privacy': {
      id: '/_public/_layout/(site)/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PublicLayoutsitePrivacyRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_public/_layout/(site)/contact': {
      id: '/_public/_layout/(site)/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof PublicLayoutsiteContactRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
  }
}

interface AuthenticatedDashboardSettingsRouteRouteChildren {
  AuthenticatedDashboardSettingsIndexRoute: typeof AuthenticatedDashboardSettingsIndexRoute
}

const AuthenticatedDashboardSettingsRouteRouteChildren: AuthenticatedDashboardSettingsRouteRouteChildren =
  {
    AuthenticatedDashboardSettingsIndexRoute:
      AuthenticatedDashboardSettingsIndexRoute,
  }

const AuthenticatedDashboardSettingsRouteRouteWithChildren =
  AuthenticatedDashboardSettingsRouteRoute._addFileChildren(
    AuthenticatedDashboardSettingsRouteRouteChildren,
  )

interface AuthenticatedDashboardRouteRouteChildren {
  AuthenticatedDashboardSettingsRouteRoute: typeof AuthenticatedDashboardSettingsRouteRouteWithChildren
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDashboardAlertsIndexRoute: typeof AuthenticatedDashboardAlertsIndexRoute
  AuthenticatedDashboardCoreConfigIndexRoute: typeof AuthenticatedDashboardCoreConfigIndexRoute
  AuthenticatedDashboardIntegrationsIndexRoute: typeof AuthenticatedDashboardIntegrationsIndexRoute
  AuthenticatedDashboardPluginsThemesIndexRoute: typeof AuthenticatedDashboardPluginsThemesIndexRoute
  AuthenticatedDashboardReportsIndexRoute: typeof AuthenticatedDashboardReportsIndexRoute
  AuthenticatedDashboardScanHistoryIndexRoute: typeof AuthenticatedDashboardScanHistoryIndexRoute
  AuthenticatedDashboardVulnerabilitiesIndexRoute: typeof AuthenticatedDashboardVulnerabilitiesIndexRoute
}

const AuthenticatedDashboardRouteRouteChildren: AuthenticatedDashboardRouteRouteChildren =
  {
    AuthenticatedDashboardSettingsRouteRoute:
      AuthenticatedDashboardSettingsRouteRouteWithChildren,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
    AuthenticatedDashboardAlertsIndexRoute:
      AuthenticatedDashboardAlertsIndexRoute,
    AuthenticatedDashboardCoreConfigIndexRoute:
      AuthenticatedDashboardCoreConfigIndexRoute,
    AuthenticatedDashboardIntegrationsIndexRoute:
      AuthenticatedDashboardIntegrationsIndexRoute,
    AuthenticatedDashboardPluginsThemesIndexRoute:
      AuthenticatedDashboardPluginsThemesIndexRoute,
    AuthenticatedDashboardReportsIndexRoute:
      AuthenticatedDashboardReportsIndexRoute,
    AuthenticatedDashboardScanHistoryIndexRoute:
      AuthenticatedDashboardScanHistoryIndexRoute,
    AuthenticatedDashboardVulnerabilitiesIndexRoute:
      AuthenticatedDashboardVulnerabilitiesIndexRoute,
  }

const AuthenticatedDashboardRouteRouteWithChildren =
  AuthenticatedDashboardRouteRoute._addFileChildren(
    AuthenticatedDashboardRouteRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRouteRoute: typeof AuthenticatedDashboardRouteRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRouteRoute:
    AuthenticatedDashboardRouteRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface PublicLayoutRouteChildren {
  PublicLayoutsiteContactRoute: typeof PublicLayoutsiteContactRoute
  PublicLayoutsitePrivacyRoute: typeof PublicLayoutsitePrivacyRoute
  PublicLayoutsiteTermsRoute: typeof PublicLayoutsiteTermsRoute
  PublicLayoutsiteIndexRoute: typeof PublicLayoutsiteIndexRoute
}

const PublicLayoutRouteChildren: PublicLayoutRouteChildren = {
  PublicLayoutsiteContactRoute: PublicLayoutsiteContactRoute,
  PublicLayoutsitePrivacyRoute: PublicLayoutsitePrivacyRoute,
  PublicLayoutsiteTermsRoute: PublicLayoutsiteTermsRoute,
  PublicLayoutsiteIndexRoute: PublicLayoutsiteIndexRoute,
}

const PublicLayoutRouteWithChildren = PublicLayoutRoute._addFileChildren(
  PublicLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  PublicLayoutRoute: PublicLayoutRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthEmailVerificationRoute: AuthEmailVerificationRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthNewPasswordRoute: AuthNewPasswordRoute,
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
