/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthSigninRouteImport } from './routes/auth/signin'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthEmailVerificationRouteImport } from './routes/auth/email-verification'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as PublicLayoutRouteImport } from './routes/_public/_layout'
import { Route as AuthenticatedDashboardRouteRouteImport } from './routes/_authenticated/dashboard/route'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedDashboardVulnerabilitiesRouteImport } from './routes/_authenticated/dashboard/vulnerabilities'
import { Route as AuthenticatedDashboardSettingsRouteImport } from './routes/_authenticated/dashboard/settings'
import { Route as AuthenticatedDashboardScanHistoryRouteImport } from './routes/_authenticated/dashboard/scan-history'
import { Route as AuthenticatedDashboardReportsRouteImport } from './routes/_authenticated/dashboard/reports'
import { Route as AuthenticatedDashboardPortsServicesRouteImport } from './routes/_authenticated/dashboard/ports-services'
import { Route as AuthenticatedDashboardIntegrationsRouteImport } from './routes/_authenticated/dashboard/integrations'
import { Route as AuthenticatedDashboardCloudAssetsRouteImport } from './routes/_authenticated/dashboard/cloud-assets'
import { Route as AuthenticatedDashboardAttackSurfaceRouteImport } from './routes/_authenticated/dashboard/attack-surface'
import { Route as AuthenticatedDashboardAlertsRouteImport } from './routes/_authenticated/dashboard/alerts'
import { Route as PublicLayoutsiteIndexRouteImport } from './routes/_public/_layout/(site)/index'
import { Route as PublicLayoutsiteTermsRouteImport } from './routes/_public/_layout/(site)/terms'
import { Route as PublicLayoutsitePrivacyRouteImport } from './routes/_public/_layout/(site)/privacy'
import { Route as PublicLayoutsiteContactRouteImport } from './routes/_public/_layout/(site)/contact'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/auth/signin',
  path: '/auth/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthEmailVerificationRoute = AuthEmailVerificationRouteImport.update({
  id: '/auth/email-verification',
  path: '/auth/email-verification',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicLayoutRoute = PublicLayoutRouteImport.update({
  id: '/_public/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRouteRoute =
  AuthenticatedDashboardRouteRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardVulnerabilitiesRoute =
  AuthenticatedDashboardVulnerabilitiesRouteImport.update({
    id: '/vulnerabilities',
    path: '/vulnerabilities',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardSettingsRoute =
  AuthenticatedDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardScanHistoryRoute =
  AuthenticatedDashboardScanHistoryRouteImport.update({
    id: '/scan-history',
    path: '/scan-history',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardReportsRoute =
  AuthenticatedDashboardReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardPortsServicesRoute =
  AuthenticatedDashboardPortsServicesRouteImport.update({
    id: '/ports-services',
    path: '/ports-services',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardIntegrationsRoute =
  AuthenticatedDashboardIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardCloudAssetsRoute =
  AuthenticatedDashboardCloudAssetsRouteImport.update({
    id: '/cloud-assets',
    path: '/cloud-assets',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardAttackSurfaceRoute =
  AuthenticatedDashboardAttackSurfaceRouteImport.update({
    id: '/attack-surface',
    path: '/attack-surface',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardAlertsRoute =
  AuthenticatedDashboardAlertsRouteImport.update({
    id: '/alerts',
    path: '/alerts',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const PublicLayoutsiteIndexRoute = PublicLayoutsiteIndexRouteImport.update({
  id: '/(site)/',
  path: '/',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const PublicLayoutsiteTermsRoute = PublicLayoutsiteTermsRouteImport.update({
  id: '/(site)/terms',
  path: '/terms',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const PublicLayoutsitePrivacyRoute = PublicLayoutsitePrivacyRouteImport.update({
  id: '/(site)/privacy',
  path: '/privacy',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const PublicLayoutsiteContactRoute = PublicLayoutsiteContactRouteImport.update({
  id: '/(site)/contact',
  path: '/contact',
  getParentRoute: () => PublicLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicLayoutsiteIndexRoute
  '/dashboard': typeof AuthenticatedDashboardRouteRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/email-verification': typeof AuthEmailVerificationRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/dashboard/alerts': typeof AuthenticatedDashboardAlertsRoute
  '/dashboard/attack-surface': typeof AuthenticatedDashboardAttackSurfaceRoute
  '/dashboard/cloud-assets': typeof AuthenticatedDashboardCloudAssetsRoute
  '/dashboard/integrations': typeof AuthenticatedDashboardIntegrationsRoute
  '/dashboard/ports-services': typeof AuthenticatedDashboardPortsServicesRoute
  '/dashboard/reports': typeof AuthenticatedDashboardReportsRoute
  '/dashboard/scan-history': typeof AuthenticatedDashboardScanHistoryRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard/vulnerabilities': typeof AuthenticatedDashboardVulnerabilitiesRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/contact': typeof PublicLayoutsiteContactRoute
  '/privacy': typeof PublicLayoutsitePrivacyRoute
  '/terms': typeof PublicLayoutsiteTermsRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicLayoutsiteIndexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/email-verification': typeof AuthEmailVerificationRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/dashboard/alerts': typeof AuthenticatedDashboardAlertsRoute
  '/dashboard/attack-surface': typeof AuthenticatedDashboardAttackSurfaceRoute
  '/dashboard/cloud-assets': typeof AuthenticatedDashboardCloudAssetsRoute
  '/dashboard/integrations': typeof AuthenticatedDashboardIntegrationsRoute
  '/dashboard/ports-services': typeof AuthenticatedDashboardPortsServicesRoute
  '/dashboard/reports': typeof AuthenticatedDashboardReportsRoute
  '/dashboard/scan-history': typeof AuthenticatedDashboardScanHistoryRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard/vulnerabilities': typeof AuthenticatedDashboardVulnerabilitiesRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/contact': typeof PublicLayoutsiteContactRoute
  '/privacy': typeof PublicLayoutsitePrivacyRoute
  '/terms': typeof PublicLayoutsiteTermsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteRouteWithChildren
  '/_public/_layout': typeof PublicLayoutRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/email-verification': typeof AuthEmailVerificationRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/_authenticated/dashboard/alerts': typeof AuthenticatedDashboardAlertsRoute
  '/_authenticated/dashboard/attack-surface': typeof AuthenticatedDashboardAttackSurfaceRoute
  '/_authenticated/dashboard/cloud-assets': typeof AuthenticatedDashboardCloudAssetsRoute
  '/_authenticated/dashboard/integrations': typeof AuthenticatedDashboardIntegrationsRoute
  '/_authenticated/dashboard/ports-services': typeof AuthenticatedDashboardPortsServicesRoute
  '/_authenticated/dashboard/reports': typeof AuthenticatedDashboardReportsRoute
  '/_authenticated/dashboard/scan-history': typeof AuthenticatedDashboardScanHistoryRoute
  '/_authenticated/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/_authenticated/dashboard/vulnerabilities': typeof AuthenticatedDashboardVulnerabilitiesRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_public/_layout/(site)/contact': typeof PublicLayoutsiteContactRoute
  '/_public/_layout/(site)/privacy': typeof PublicLayoutsitePrivacyRoute
  '/_public/_layout/(site)/terms': typeof PublicLayoutsiteTermsRoute
  '/_public/_layout/(site)/': typeof PublicLayoutsiteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/auth/callback'
    | '/auth/email-verification'
    | '/auth/forgot-password'
    | '/auth/signin'
    | '/auth/signup'
    | '/dashboard/alerts'
    | '/dashboard/attack-surface'
    | '/dashboard/cloud-assets'
    | '/dashboard/integrations'
    | '/dashboard/ports-services'
    | '/dashboard/reports'
    | '/dashboard/scan-history'
    | '/dashboard/settings'
    | '/dashboard/vulnerabilities'
    | '/dashboard/'
    | '/contact'
    | '/privacy'
    | '/terms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/callback'
    | '/auth/email-verification'
    | '/auth/forgot-password'
    | '/auth/signin'
    | '/auth/signup'
    | '/dashboard/alerts'
    | '/dashboard/attack-surface'
    | '/dashboard/cloud-assets'
    | '/dashboard/integrations'
    | '/dashboard/ports-services'
    | '/dashboard/reports'
    | '/dashboard/scan-history'
    | '/dashboard/settings'
    | '/dashboard/vulnerabilities'
    | '/dashboard'
    | '/contact'
    | '/privacy'
    | '/terms'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/dashboard'
    | '/_public/_layout'
    | '/auth/callback'
    | '/auth/email-verification'
    | '/auth/forgot-password'
    | '/auth/signin'
    | '/auth/signup'
    | '/_authenticated/dashboard/alerts'
    | '/_authenticated/dashboard/attack-surface'
    | '/_authenticated/dashboard/cloud-assets'
    | '/_authenticated/dashboard/integrations'
    | '/_authenticated/dashboard/ports-services'
    | '/_authenticated/dashboard/reports'
    | '/_authenticated/dashboard/scan-history'
    | '/_authenticated/dashboard/settings'
    | '/_authenticated/dashboard/vulnerabilities'
    | '/_authenticated/dashboard/'
    | '/_public/_layout/(site)/contact'
    | '/_public/_layout/(site)/privacy'
    | '/_public/_layout/(site)/terms'
    | '/_public/_layout/(site)/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  PublicLayoutRoute: typeof PublicLayoutRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthEmailVerificationRoute: typeof AuthEmailVerificationRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/auth/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/email-verification': {
      id: '/auth/email-verification'
      path: '/auth/email-verification'
      fullPath: '/auth/email-verification'
      preLoaderRoute: typeof AuthEmailVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/_layout': {
      id: '/_public/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/vulnerabilities': {
      id: '/_authenticated/dashboard/vulnerabilities'
      path: '/vulnerabilities'
      fullPath: '/dashboard/vulnerabilities'
      preLoaderRoute: typeof AuthenticatedDashboardVulnerabilitiesRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/settings': {
      id: '/_authenticated/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/scan-history': {
      id: '/_authenticated/dashboard/scan-history'
      path: '/scan-history'
      fullPath: '/dashboard/scan-history'
      preLoaderRoute: typeof AuthenticatedDashboardScanHistoryRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/reports': {
      id: '/_authenticated/dashboard/reports'
      path: '/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof AuthenticatedDashboardReportsRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/ports-services': {
      id: '/_authenticated/dashboard/ports-services'
      path: '/ports-services'
      fullPath: '/dashboard/ports-services'
      preLoaderRoute: typeof AuthenticatedDashboardPortsServicesRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/integrations': {
      id: '/_authenticated/dashboard/integrations'
      path: '/integrations'
      fullPath: '/dashboard/integrations'
      preLoaderRoute: typeof AuthenticatedDashboardIntegrationsRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/cloud-assets': {
      id: '/_authenticated/dashboard/cloud-assets'
      path: '/cloud-assets'
      fullPath: '/dashboard/cloud-assets'
      preLoaderRoute: typeof AuthenticatedDashboardCloudAssetsRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/attack-surface': {
      id: '/_authenticated/dashboard/attack-surface'
      path: '/attack-surface'
      fullPath: '/dashboard/attack-surface'
      preLoaderRoute: typeof AuthenticatedDashboardAttackSurfaceRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/alerts': {
      id: '/_authenticated/dashboard/alerts'
      path: '/alerts'
      fullPath: '/dashboard/alerts'
      preLoaderRoute: typeof AuthenticatedDashboardAlertsRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_public/_layout/(site)/': {
      id: '/_public/_layout/(site)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicLayoutsiteIndexRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_public/_layout/(site)/terms': {
      id: '/_public/_layout/(site)/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof PublicLayoutsiteTermsRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_public/_layout/(site)/privacy': {
      id: '/_public/_layout/(site)/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PublicLayoutsitePrivacyRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_public/_layout/(site)/contact': {
      id: '/_public/_layout/(site)/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof PublicLayoutsiteContactRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
  }
}

interface AuthenticatedDashboardRouteRouteChildren {
  AuthenticatedDashboardAlertsRoute: typeof AuthenticatedDashboardAlertsRoute
  AuthenticatedDashboardAttackSurfaceRoute: typeof AuthenticatedDashboardAttackSurfaceRoute
  AuthenticatedDashboardCloudAssetsRoute: typeof AuthenticatedDashboardCloudAssetsRoute
  AuthenticatedDashboardIntegrationsRoute: typeof AuthenticatedDashboardIntegrationsRoute
  AuthenticatedDashboardPortsServicesRoute: typeof AuthenticatedDashboardPortsServicesRoute
  AuthenticatedDashboardReportsRoute: typeof AuthenticatedDashboardReportsRoute
  AuthenticatedDashboardScanHistoryRoute: typeof AuthenticatedDashboardScanHistoryRoute
  AuthenticatedDashboardSettingsRoute: typeof AuthenticatedDashboardSettingsRoute
  AuthenticatedDashboardVulnerabilitiesRoute: typeof AuthenticatedDashboardVulnerabilitiesRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteRouteChildren: AuthenticatedDashboardRouteRouteChildren =
  {
    AuthenticatedDashboardAlertsRoute: AuthenticatedDashboardAlertsRoute,
    AuthenticatedDashboardAttackSurfaceRoute:
      AuthenticatedDashboardAttackSurfaceRoute,
    AuthenticatedDashboardCloudAssetsRoute:
      AuthenticatedDashboardCloudAssetsRoute,
    AuthenticatedDashboardIntegrationsRoute:
      AuthenticatedDashboardIntegrationsRoute,
    AuthenticatedDashboardPortsServicesRoute:
      AuthenticatedDashboardPortsServicesRoute,
    AuthenticatedDashboardReportsRoute: AuthenticatedDashboardReportsRoute,
    AuthenticatedDashboardScanHistoryRoute:
      AuthenticatedDashboardScanHistoryRoute,
    AuthenticatedDashboardSettingsRoute: AuthenticatedDashboardSettingsRoute,
    AuthenticatedDashboardVulnerabilitiesRoute:
      AuthenticatedDashboardVulnerabilitiesRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteRouteWithChildren =
  AuthenticatedDashboardRouteRoute._addFileChildren(
    AuthenticatedDashboardRouteRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRouteRoute: typeof AuthenticatedDashboardRouteRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRouteRoute:
    AuthenticatedDashboardRouteRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface PublicLayoutRouteChildren {
  PublicLayoutsiteContactRoute: typeof PublicLayoutsiteContactRoute
  PublicLayoutsitePrivacyRoute: typeof PublicLayoutsitePrivacyRoute
  PublicLayoutsiteTermsRoute: typeof PublicLayoutsiteTermsRoute
  PublicLayoutsiteIndexRoute: typeof PublicLayoutsiteIndexRoute
}

const PublicLayoutRouteChildren: PublicLayoutRouteChildren = {
  PublicLayoutsiteContactRoute: PublicLayoutsiteContactRoute,
  PublicLayoutsitePrivacyRoute: PublicLayoutsitePrivacyRoute,
  PublicLayoutsiteTermsRoute: PublicLayoutsiteTermsRoute,
  PublicLayoutsiteIndexRoute: PublicLayoutsiteIndexRoute,
}

const PublicLayoutRouteWithChildren = PublicLayoutRoute._addFileChildren(
  PublicLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  PublicLayoutRoute: PublicLayoutRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthEmailVerificationRoute: AuthEmailVerificationRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
